import { useEffect, Component } from 'react'
import { BrowserRouter, Routes, Route, useLocation, useNavigate } from 'react-router-dom'
import Header               from './components/Header'
import Footer               from './components/Footer'
import Home                 from './pages/Home'
import CategoryPage         from './pages/CategoryPage'
import ProvidersPage        from './pages/ProvidersPage'
import RegistroProveedoresPage from './pages/RegistroProveedoresPage'
import LoginPage            from './pages/LoginPage'
import ProviderDashboard    from './pages/ProviderDashboard'
import ResetPasswordPage    from './pages/ResetPasswordPage'
import AdminPanel           from './pages/AdminPanel'
// import PricingPage          from './pages/PricingPage'          // desactivado — período gratuito
import VerificacionPage     from './pages/VerificacionPage'
import ProviderPage         from './pages/ProviderPage'
import FirstStepsPage       from './pages/FirstStepsPage'
import MigrantAccountPage   from './pages/MigrantAccountPage'
import BookingRoom          from './pages/BookingRoom'
import OpinarPage           from './pages/OpinarPage'
import BaggagePage          from './pages/BaggagePage'
// import PaymentSuccessPage   from './pages/PaymentSuccessPage'   // desactivado — período gratuito
// import PaymentCancelPage    from './pages/PaymentCancelPage'    // desactivado — período gratuito
import ProtectedRoute       from './components/ProtectedRoute'
import RemesasFloat        from './components/RemesasFloat'
import { AuthProvider }     from './hooks/useAuth'
// IMPORTANTE: Se eliminó initScrollTracking de la siguiente línea
import { useTranslation } from 'react-i18next'
import { trackPageView } from './utils/analytics'
